#!/bin/sh

# Se l'argomento è un numero, cerca ed esegue la riga corrispondente
if [[ $1 =~ ^[0-9]+$ ]]; then
    # Estrae la riga N, rimuove il prefisso "# SCR: " e la esegue
riga=$(( $1 + 26 ))
cmd=$(sed -n "${riga}p" "$0" )

    if [ -z "$cmd" ]; then
        echo "Error: nothing found at $1"
    else
        eval "$cmd"
    fi
    exit 0
fi

# Se l'argomento è un testo (non numero), lo aggiunge in coda come commento speciale
if [ "$#" -gt 0 ] ; then
    echo "#$@" >> "$0"
    echo "Saved at: $(( $(wc -l < "$0") - 26 ))"
    exit 0
fi
tail -n +26 utils
: <<'Commento'

mount -t ntfs-3g /dev/sda2 /mnt/hdd/ ; cd /mnt/hdd/Windows.old/Users/ColomBonini/me/
btop
export MICRO_TRUECOLOR=1
export TCELL_TRUECOLOR=1
git add .; git commit -m f; git push 
echo 1 > /sys/class/leds/input0::capslock/brightness
Commento
